### ISSUE TITLE
Geth PreState tracer has problems

### ISSUE THREAD

**Issue by koinov** [paradigmxyz/evm-inspectors#13]
It looks like PreStateTracer with diff_mode = Some(false) or None that means it collects initial state for the transaction returns intermediate value. If there's SSTORE(key, 1) SSTORE(key, 0) it returns 1, maybe it depends on SLOAD(key) used in between. 

I guess the problem is, when you setup touched cells here : https://github.com/paradigmxyz/evm-inspectors/blob/5ee90076f88e64a059e4c0c268929cf9ec91ed6d/src/tracing/builder/geth.rs#L205)

you should overwrite values even if they are already in the storage with 
`entry.insert(slot.previous_or_original_value.into());`
here
https://github.com/paradigmxyz/evm-inspectors/blob/5ee90076f88e64a059e4c0c268929cf9ec91ed6d/src/tracing/builder/geth.rs#L241

I found the problem with reth 0.16-alpha from todays main, checked my code with infura, and there's a difference indeed. With state from Infura transaction is commited well to REMV, however with Reth it looks like UniswapV3 lock is locked from the beginning.

**Comment by mattsse** [comment]
do you have an example request I can use for debugging?

**Comment by koinov** [comment]
I guess this one:

`{
method:"debug_traceTransaction",
params:[
"0xd0e0a6a5f3ec107e97a15ca91aeb3e45168fa5e2df143d12952764ec0f66cce8",
{
tracer:"prestateTracer",
tracerConfig:{
diffMode:false
}
}
],
id:4,
jsonrpc:"2.0"
}`

**Comment by mattsse** [comment]
thanks, checking

**Comment by dexloom** [comment]
Looks like the same problem with:

`{ method:"debug_traceTransaction", params:[ "0x0def9bd26edcd94ad3d9a7269de062d2bf34682f25c2fdcae91360241fd82351", { tracer:"prestateTracer", tracerConfig:{ diffMode:false } } ], id:4, jsonrpc:"2.0" }`

This time transaction is reverted, do not know if it matters or not.

**Comment by dexloom** [comment]
I made short code for checking difference, can publish it later today : 

[2024-02-14T09:34:07Z ERROR revmcheck] Cell not found geth->reth address: 0x3fC91A3afd70395Cd496C647d5a6CC9D4B2b7FAD cell : 0x0000000000000000000000000000000000000000000000000000000000000001
[2024-02-14T09:34:07Z ERROR revmcheck] Target state not found for address geth->reth 0x90e7a93E0a6514CB0c84fC7aCC1cb5c0793352d2
[2024-02-14T09:34:07Z ERROR revmcheck] Target state not found for address geth->reth 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
[2024-02-14T09:34:07Z ERROR revmcheck] Target state not found for address geth->reth 0xE73d53e3a982ab2750A0b76F9012e18B256Cc243
