### ISSUE TITLE
Add `muxTracer` to use multiple tracers in a single trace call

### ISSUE THREAD

**Issue by ArtificialPB** [paradigmxyz/evm-inspectors#49]
Useful for getting multiple tracer results in a single call, e.g. logs via `callTracer` along with statediff via `prestateTracer`.

Reference implementation in go-ethereum: https://github.com/ethereum/go-ethereum/blob/master/eth/tracers/native/mux.go

**Comment by mattsse** [comment]
@DoTheBestToGetTheBest do you want to take this?

**Comment by ArtificialPB** [comment]
@mattsse I plan to take this later this week
